name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: "package.json"

    - name: Setup pnpm
      uses: pnpm/action-setup@v2

    - name: Install VS Code Extension Manager
      run: pnpm install --global vsce

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Theme
      run: pnpm build

    - name: Publish Theme
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: pnpm pub

    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: pnpm release
